### ISSUE TITLE
Routing issue

### ISSUE THREAD

**Issue by BuddhikaD** [Satriaana/Satriaana-Web-Site#102]
When we deploy the site it's URL display as `https://satriaana.github.io/Satriaana-Web-Site/#/` including `#` , we want to remove the hash from the url in react-router

**Comment by bhattaraib58** [comment]
can i take this @BuddhikaD ?

**Comment by BuddhikaD** [comment]
Sure go ahead! do you want to be assigned for this issue?

**Comment by bhattaraib58** [comment]
@BuddhikaD  ya sure, please assign me.

**Comment by BuddhikaD** [comment]
Okay 😊

**Comment by iampankajgupta** [comment]
can i work on this issue

**Comment by bhattaraib58** [comment]
@BuddhikaD  the issue has been fixed, you can review the PR, https://github.com/Satriaana/Satriaana-Web-Site/pull/103

**Comment by BuddhikaD** [comment]
Hi @bhattaraib58 ,

I have reviewed your pull request. Great work!

Thank you so much for your generous contributions to the GitHub issues regarding the website of Satriaana. We highly appreciate all the work you’ve done. Your efforts in developing our website are very commendable.

It’s with great pleasure that we’d like to inform you that we've decided to give you the chance of joining us as volunteers, after seeing your enthusiasm for open-source. So, if you’re interested, simply fill out the form through the link we’ve attached forthwith.

Note: We’re starting our volunteer onboard process in three weeks time from now on and we’re sending this form only to you as you have contributed to our website. Hence we’ll be closing the link of the form right after you’ve submitted the form. So, we would like to kindly request you to send us a message in reply after you’ve filled it.

Volunteer Form: https://satriaana.typeform.com/to/XYGqfnkI

Hope we can work together again very soon!

**Comment by nimeshkavinda** [comment]
> @BuddhikaD  the issue has been fixed, you can review the PR, https://github.com/Satriaana/Satriaana-Web-Site/pull/103

Hi @bhattaraib58 ,
I have reviewed your PR, Although it does fix our initial issue, it also creates a new issue where you can't go to an external link and come back to the site as it will return a 404 error. Could you please look into that?

Example: Try clicking on either 'blog' or 'forum' on navbar and clicking on back button of ur browser. It will return a 404 error.

**Comment by bhattaraib58** [comment]
@nimeshkavinda  ya it's because of github pages you guys are using for hosting the pages as it appends /Satriaana-Web-Site/ to every route. I will look more into this issue today.

**Comment by bhattaraib58** [comment]
@BuddhikaD @nimeshkavinda  you guys could try heroku or netlify, both offer free services and offer automatic deployments as well. As well as auto CI/CD where when code is merged into master the beach gets auto deployed to site.

Also, it won't have the appended /Satriaana-Web-Site/ on the route.

**Comment by nimeshkavinda** [comment]
> @BuddhikaD @nimeshkavinda you guys could try heroku or netlify, both offer free services and offer automatic deployments as well. As well as auto CI/CD where when code is merged into master the beach gets auto deployed to site.
> 
> Also, it won't have the appended /Satriaana-Web-Site/ on the route.

@bhattaraib58 They are great platforms for sure! we do plan on hosting this site outside of Github pages once its ready. Atm its only hosted on Github pages for development and testing purpose.

For now, could you please look into the issue where it resets the route to 'satriaana.github.io' instead of 'satriaana.github.io/Satriaana-Web-Site' when you click on back? Other than that, everything else is working just fine.

**Comment by bhattaraib58** [comment]
@nimeshkavinda ok sure, I will look into this issue today.

**Comment by nimeshkavinda** [comment]
> @nimeshkavinda ok sure, I will look into this issue today.

Great! thank you

**Comment by nimeshkavinda** [comment]
Hi, @bhattaraib58 

Thank you so much for your generous contributions to the GitHub issues regarding the website of Satriaana. We highly appreciate all the work you’ve done. Your efforts in developing our website are very commendable.

It’s with great pleasure that we’d like to inform you that we've decided to give you the chance of joining us as volunteers, after seeing your enthusiasm for open-source. So, if you’re interested, simply fill out the form through the link we’ve attached forthwith.

Note: We’re starting our volunteer onboard process in three weeks time from now on and we’re sending this form only to you as you have contributed to our website. Hence we’ll be closing the link of the form right after you’ve submitted the form. So, we would like to kindly request you to send us a message in reply after you’ve filled it.

Volunteer Form: https://satriaana.typeform.com/to/XYGqfnkI

Hope we can work together again very soon!

**Comment by bhattaraib58** [comment]
@nimeshkavinda cc: @BuddhikaD,
Thank you for your generous offer.
But with a heavy heart, I will have to reject the offer for now. It's just that I am involved in lots of projects and many organizations,
And it will be hard for me to handle all the moving pieces (As it's the current scenario now).

I will contact you guys in the future when I get a chance to hop on to other tasks. 
And ya, let's hope our paths cross soon.

**Comment by nimeshkavinda** [comment]
> @nimeshkavinda cc: @BuddhikaD,
> Thank you for your generous offer.
> But with a heavy heart, I will have to reject the offer for now. It's just that I am involved in lots of projects and many organizations,
> And it will be hard for me to handle all the moving pieces (As it's the current scenario now).
> 
> I will contact you guys in the future when I get a chance to hop on to other tasks.
> And ya, let's hope our paths cross soon.

No worries! :D
May we work again in the future
