### ISSUE TITLE
Idea for code structure

### ISSUE THREAD

**Issue by inovux** [Satriaana/Satriaana-Web-Site#107]
Hello there :)

I was wondering whether it was a good idea to split up your pages into a separate folder, since they are all inside your components folder right now. I think its much better to have all your base components in the `components` folder and the pages in a separate `pages` folder.

**Comment by BuddhikaD** [comment]
@inovux Hello thank for your message.. if you like to rearrange this component in to nicer and clean build then feel free to tell us we like to assign you to this issue🤗

**Comment by st-currenxie** [comment]
> @inovux Hello thank for your message.. if you like to rearrange this component in to nicer and clean build then feel free to tell us we like to assign you to this issue🤗

Sure assign me :)

**Comment by inovux** [comment]
Sure assign me :)

**Comment by BuddhikaD** [comment]
Sure I'll assign you .. go ahead! 😊

**Comment by ghost** [comment]
I see that this has been reopened, What is the current issue?

**Comment by inovux** [comment]
@BuddhikaD Can we split this up in several issues? I made a start so this issue can be closed.

What I am thinking is create an issue for cleaning up every single page: `home`, `contact`, and `about`. There are a lot more minor improvements we can do but this would be a nice start imo :)

**Comment by ghost** [comment]
Yeah I can take a look through your pages over the next couple of days and
clean it up a little :)

**Comment by BuddhikaD** [comment]
@inovux Hey look at.. i created a new issues for cleaning

**Comment by st-currenxie** [comment]
@BuddhikaD Awesome thanks!

**Comment by ghost** [comment]
I will check this out tomorrow :)

**Comment by inovux** [comment]
@BuddhikaD Awesome thanks !

**Comment by BuddhikaD** [comment]
@pearlslugs  Okay not a problem 😊

**Comment by BuddhikaD** [comment]
I will close this issue so there is no problem
