### ISSUE TITLE
cleaning up About code structure 

### ISSUE THREAD

**Issue by BuddhikaD** [Satriaana/Satriaana-Web-Site#113]

**Comment by inovux** [comment]
@BuddhikaD Can you assign this one to me :)?

**Comment by BuddhikaD** [comment]
Sure 😊

**Comment by inovux** [comment]
@BuddhikaD Does your community have a discord or something similar. Might be easier to plan some things over there before adding them as issues as well :)

**Comment by BuddhikaD** [comment]
Hey we like to invite you to our organisation ...
 Hi, @inovux 

Thank you so much for your generous contributions to the GitHub issues regarding the website of Satriaana. We highly appreciate all the work you’ve done. Your efforts in developing our website are very commendable.

It’s with great pleasure that we’d like to inform you that we've decided to give you the chance of joining us as volunteers, after seeing your enthusiasm for open-source. So, if you’re interested, simply fill out the form through the link we’ve attached forthwith.

Note: We’re starting our volunteer onboard process in three weeks time from now on and we’re sending this form only to you as you have contributed to our website. Hence we’ll be closing the link of the form right after you’ve submitted the form. So, we would like to kindly request you to send us a message in reply after you’ve filled it.

Volunteer Form: https://satriaana.typeform.com/to/XYGqfnkI

Hope we can work together soon !!!!!

**Comment by inovux** [comment]
@BuddhikaD I have already filled ur form :) Thanks

**Comment by inovux** [comment]
@BuddhikaD PR is created let me know if you have any comments :)

**Comment by BuddhikaD** [comment]
Sure i'll check it and tell you 😊
