### ISSUE TITLE
clean up Footer component

### ISSUE THREAD

**Issue by inovux** [Satriaana/Satriaana-Web-Site#115]
TODO:

* This component should be styled with CSS Modules;
* Reuse existing components inside this component;
* Write new reusable components where necessary;

**Comment by BuddhikaD** [comment]
Hey your are good a man 😁 nice opensource contributor .. if you like to assign this task

**Comment by inovux** [comment]
@BuddhikaD I think the components still need to be cleaned up. I didnt have the time to do it get, but I think keeping it open will make it possible for others to contribute too :)
