### ISSUE TITLE
Create reusable Input component

### ISSUE THREAD

**Issue by inovux** [Satriaana/Satriaana-Web-Site#116]
# Create a reusable input component

**Input should look like the following:**

<img width="898" alt="Screen Shot 2020-10-09 at 4 56 54 PM" src="https://user-images.githubusercontent.com/12704461/95563801-787c3700-0a50-11eb-8759-90cdf1a00959.png">

**Props it should accept:**

* placeholder
* type
* value
* onChange

This component will only be used on the contact page for now.

**Comment by inovux** [comment]
@BuddhikaD Please assign this one to me if you agree with this :)

**Comment by BuddhikaD** [comment]
Okay not a problem... Sure i'll assign you..
Thank for filling  our organisation invitation link we'll contact you soon..

**Comment by BuddhikaD** [comment]
If you have any problem feel free to contact me..
Telegram := https://t.me/BuddhikaD
Discord := @ Buddhika Dananjaya#8268
