### ISSUE TITLE
Dark mode toggle in React

### ISSUE THREAD

**Issue by nimeshkavinda** [Satriaana/Satriaana-Web-Site#69]
Need to develop a light/ dark mode toggle for the site :crescent_moon:

Find more info: [https://github.com/Satriaana/Satriaana-Web-Site/blob/dev/README.md](https://github.com/Satriaana/Satriaana-Web-Site/blob/dev/README.md)

**Comment by cap-code** [comment]
i can do it

**Comment by nimeshkavinda** [comment]
> i can do it assign it to me

There, I have assigned you for the issue. :smile:

**Comment by iampankajgupta** [comment]
can i try to solve this  issue

**Comment by nimeshkavinda** [comment]
> can i try to solve this issue

Sure thing!

**Comment by iampankajgupta** [comment]
I'm done with issue but i'm  getting conflict while raising pull request

**Comment by iampankajgupta** [comment]
can you review my PR

**Comment by BuddhikaD** [comment]
Hi, @iampankajgupta 

Thank you so much for your generous contributions to the GitHub issues regarding the website of Satriaana. We highly appreciate all the work you’ve done. Your efforts in developing our website are very commendable.

It’s with great pleasure that we’d like to inform you that we've decided to give you the chance of joining us as volunteers, after seeing your enthusiasm for open-source. So, if you’re interested, simply fill out the form through the link we’ve attached forthwith.

Note: We’re starting our volunteer onboard process in three weeks time from now on and we’re sending this form only to you as you have contributed to our website. Hence we’ll be closing the link of the form right after you’ve submitted the form. So, we would like to kindly request you to send us a message in reply after you’ve filled it.

Volunteer Form: https://satriaana.typeform.com/to/XYGqfnkI

Hope we can work together again very soon!

**Comment by iampankajgupta** [comment]
i think you have closed the issue i.e why I'm not able to create pull request

**Comment by nimeshkavinda** [comment]
> i think you have closed the issue i.e why I'm not able to create pull request

Hi, I have left you with a note in your pull request.
