### ISSUE TITLE
Twitter feed that can update in real-time

### ISSUE THREAD

**Issue by nimeshkavinda** [Satriaana/Satriaana-Web-Site#70]
Need to develop a twitter feed section which can update in real-time with the recent tweets of an account.
Feel free to make changes to the existing design of the twitter feed if required. :relaxed:

Find more info: [https://github.com/Satriaana/Satriaana-Web-Site/blob/dev/README.md](https://github.com/Satriaana/Satriaana-Web-Site/blob/dev/README.md)

**Comment by Lukydemboy** [comment]
I can do this, you can assign it to me if you want!

**Comment by TaarnStar** [comment]
Hi @nimeshkavinda, I would like to try doing this task.

**Comment by nimeshkavinda** [comment]
> Hi @nimeshkavinda, I would like to try doing this task.

Hi, @TaarnStar
Please go ahead! Feel free to mention me if you run into any problem. :smile:

**Comment by happycoder0011** [comment]
Hey, can I try too!

**Comment by nimeshkavinda** [comment]
> Hey, can I try too!

Hi @happycoder0011 Yes go ahead!

**Comment by BuddhikaD** [comment]
Hi, @saikumar221 

Thank you so much for your generous contributions to the GitHub issues regarding the website of Satriaana. We highly appreciate all the work you’ve done. Your efforts in developing our website are very commendable.

It’s with great pleasure that we’d like to inform you that we've decided to give you the chance of joining us as volunteers, after seeing your enthusiasm for open-source. So, if you’re interested, simply fill out the form through the link we’ve attached forthwith.

Note: We’re starting our volunteer onboard process in three weeks time from now on and we’re sending this form only to you as you have contributed to our website. Hence we’ll be closing the link of the form right after you’ve submitted the form. So, we would like to kindly request you to send us a message in reply after you’ve filled it.

Volunteer Form: https://satriaana.typeform.com/to/XYGqfnkI

Hope we can work together again very soon!

**Comment by nimeshkavinda** [comment]
Issue fixed.

**Comment by saikumar221** [comment]
Hello @BuddhikaD,

Thanks for the generous words! I'll always be delighted to contribute more to the open-source. I have filled out the form, Excited to learn, contribute, and build cool stuff!

> Hi, @saikumar221
> 
> Thank you so much for your generous contributions to the GitHub issues regarding the website of Satriaana. We highly appreciate all the work you’ve done. Your efforts in developing our website are very commendable.
> 
> It’s with great pleasure that we’d like to inform you that we've decided to give you the chance of joining us as volunteers, after seeing your enthusiasm for open-source. So, if you’re interested, simply fill out the form through the link we’ve attached forthwith.
> 
> Note: We’re starting our volunteer onboard process in three weeks time from now on and we’re sending this form only to you as you have contributed to our website. Hence we’ll be closing the link of the form right after you’ve submitted the form. So, we would like to kindly request you to send us a message in reply after you’ve filled it.
> 
> Volunteer Form: https://satriaana.typeform.com/to/XYGqfnkI
> 
> Hope we can work together again very soon!
