### ISSUE TITLE
Local images not being loaded when running on development server, React

### ISSUE THREAD

**Issue by nimeshkavinda** [Satriaana/Satriaana-Web-Site#71]
The site uses the local directory, 'public' for its images. When run on development server, the images does not load. :cactus:

Find more info: [https://github.com/Satriaana/Satriaana-Web-Site/blob/dev/README.md](https://github.com/Satriaana/Satriaana-Web-Site/blob/dev/README.md)

**Comment by deepank120896** [comment]
I would Like to Work on this @nimeshkavinda

**Comment by nimeshkavinda** [comment]
> I would Like to Work on this @nimeshkavinda

Great! do you want to be assigned for this issue?

**Comment by deepank120896** [comment]
@nimeshkavinda I am working on this.

**Comment by BuddhikaD** [comment]
@deepank120896 okay i,ll assign you
