### ISSUE TITLE
Google fonts not loading on Linux platforms, React

### ISSUE THREAD

**Issue by nimeshkavinda** [Satriaana/Satriaana-Web-Site#73]
Some browsers and linux operating systems does not load the used font, [Kumbh Sans](https://fonts.google.com/specimen/Kumbh+Sans?category=Sans+Serif). In addition to [Kumbh Sans](https://fonts.google.com/specimen/Kumbh+Sans?category=Sans+Serif), we also use [Poppins](https://fonts.google.com/specimen/Poppins) in case [Kumbh Sans](https://fonts.google.com/specimen/Kumbh+Sans?category=Sans+Serif) fails to load, still there are times where neither is loaded on linux platforms.

Find more info: [https://github.com/Satriaana/Satriaana-Web-Site/blob/dev/README.md](https://github.com/Satriaana/Satriaana-Web-Site/blob/dev/README.md)

**Comment by deepank120896** [comment]
Can I pick this? @nimeshkavinda

**Comment by nimeshkavinda** [comment]
> Can I pick this? @nimeshkavinda

You sure can! shall I assign you?

**Comment by nimeshkavinda** [comment]
Fixed.
