### ISSUE TITLE
Develop web-pages in React

### ISSUE THREAD

**Issue by nimeshkavinda** [Satriaana/Satriaana-Web-Site#74]
Develop an about page for the existing site.

**Proposed UI for the About page**

__About Page - Webview__

![About Page - Webview](https://i.ibb.co/ZJ0dXBF/About.png)

__About Page - Mobile View__

![About Page - Webview](https://i.ibb.co/6PZWkpw/About-Mobile.png)

Find more info: [https://github.com/Satriaana/Satriaana-Web-Site/blob/dev/README.md](https://github.com/Satriaana/Satriaana-Web-Site/blob/dev/README.md)

**Comment by jpacsai** [comment]
hi :) can I work on this issue?

**Comment by nimeshkavinda** [comment]
> hi :) can I work on this issue?

Yes! :) Let me know if you want me to assign you for the issue.

**Comment by ProCode2** [comment]
> hi :) can I work on this issue?

Hey, I am interested in this one too! Are you up for collab?

**Comment by jpacsai** [comment]
yes, please assign me :)

**Comment by nimeshkavinda** [comment]
> > hi :) can I work on this issue?
> 
> Hey, I am interested in this one too! Are you up for collab?

Hi, I have assigned you both. Good luck!

**Comment by ProCode2** [comment]
@nimeshkavinda Hey thanks!

@jpacsai lemme know.

**Comment by jpacsai** [comment]
@ProCode2 how would you like to split this up?

**Comment by ProCode2** [comment]
component wise? since we are both doing this one,I think splitting the work will be more efficient rather than both of us doing all of it. You(or me) can fork the repo and then the other of us can contribute to that forked repo, instead of directly contributing to this one.

did that make sense? :)

**Comment by jpacsai** [comment]
sure, sounds good :)

**Comment by jpacsai** [comment]
here's my fork: https://github.com/jpacsai/Satriaana-Web-Site

**Comment by Rasikamurali** [comment]
hi can I work on this issue?

**Comment by nimeshkavinda** [comment]
> hi can I work on this issue?

Hi, yes!

**Comment by nimeshkavinda** [comment]
Feel free to open a PR whenever you are done. Good luck!

**Comment by jpacsai** [comment]
@ProCode2 what if you do the jsx part and I do the styling? or vice versa :)

**Comment by ProCode2** [comment]
@jpacsai got the fork, will be cloning in a sec. 

Thats a great idea! you can choose whatever you are comfortable with, i'm good with any of the both(jsx or styling)

**Comment by jpacsai** [comment]
I'm happy with either too, but let's go with styling this time :D

**Comment by ProCode2** [comment]
sure, I am creating the basic files, and doing a test PR. then we can start at full force. Do we discuss here? (don't have a problem tho)

@nimeshkavinda Just saw that none of the header goes to a route or a section now. The About should be a section in the home page right? or you want it to stay in a separate route? for example: `http://localhost:3000/Satriaana-Web-Site/about` in the localhost.

**Comment by nimeshkavinda** [comment]
> sure, I am creating the basic files, and doing a test PR. then we can start at full force. Do we discuss here? (don't have a problem tho)
> 
> @nimeshkavinda Just saw that none of the header goes to a route or a section now. The About should be a section in the home page right? or you want it to stay in a separate route? for example: `http://localhost:3000/Satriaana-Web-Site/about` in the localhost.

Separate would be fine.

**Comment by jpacsai** [comment]
@ProCode2 are you on Slack? we can open a workspace there or if you know a better platform I'm up to it

**Comment by ProCode2** [comment]
@jpacsai yep, slack sounds good! Can you create a workspace now? I will just do the test PR

**Comment by jpacsai** [comment]
Are you on linkedIn @ProCode2 ? I can send you the invitation link there if you look me up "Judit Pacsai"

**Comment by ProCode2** [comment]
nope I am not in linkedin. You do not seem to be on twitter. You can Invite via email: bpro249@gmail.com

**Comment by jpacsai** [comment]
added you :)

**Comment by jpacsai** [comment]
@Rasikamurali it's ready, I have opened a pull request.
@ProCode2 it was a pleasure to work with you :)

**Comment by nimeshkavinda** [comment]
> @Rasikamurali it's ready, I have opened a pull request.
> @ProCode2 it was a pleasure to work with you :)

Hi @jpacsai @ProCode2,

Great work!

Before I close the issue,

Sorry for taking too long to appreciate your amazing contribution towards the development of our website. 

Here at Satriaana, we are on look for open-source enthusiasts like you. Therefore we would like to invite you both onboard as volunteers! 

If you are interested, please let us know your emails, so we could communicate with you officially.

I'll be closing this thread in 24-hours, so let me know before-hand. :relaxed:

Thanks,
Nimesh Kavinda,
Design Team,
Satriaana,

**Comment by nimeshkavinda** [comment]
> @Rasikamurali it's ready, I have opened a pull request.
> @ProCode2 it was a pleasure to work with you :)

Hi, @jpacsai @ProCode2 

Thank you so much for your generous contributions to the GitHub issues regarding the website of Satriaana. We highly appreciate all the work you’ve done. Your efforts in developing our website are very commendable.

It’s with great pleasure that we’d like to inform you that we've decided to give you the chance of joining us as volunteers, after seeing your enthusiasm for open-source. So, if you’re interested, simply fill out the form through the link we’ve attached forthwith.

Note:  We’re starting our volunteer onboard process in three weeks time from now on and we’re sending this form only to you as you have contributed to our website. Hence we’ll be closing the link of the form right after you’ve submitted the form. So, we would like to kindly request you to send us a message in reply after you’ve filled it.

Volunteer Form: [https://satriaana.typeform.com/to/XYGqfnkI](https://satriaana.typeform.com/to/XYGqfnkI)

Hope we can work together again very soon!

**Comment by ProCode2** [comment]
@nimeshkavinda glad you liked our work!

Done filling the form :)

**Comment by nimeshkavinda** [comment]
> @nimeshkavinda glad you liked our work!
> 
> Done filling the form :)

Great! We will get back to you soon :relaxed:

**Comment by nimeshkavinda** [comment]
Issue fixed.

**Comment by ProCode2** [comment]
@nimeshkavinda Hey, sending this because The email ID I submitted through the form is disabled at the moment. If you are sending more details about the volunteer work, please let me know if I can send you another email from my current email. We can continue the conversation there.🙂

**Comment by nimeshkavinda** [comment]
> @nimeshkavinda Hey, sending this because The email ID I submitted through the form is disabled at the moment. If you are sending more details about the volunteer work, please let me know if I can send you another email from my current email. We can continue the conversation there.🙂

Yes, please go ahead.
