### ISSUE TITLE
Develop web-page in React

### ISSUE THREAD

**Issue by nimeshkavinda** [Satriaana/Satriaana-Web-Site#84]
Develop a Contact page for the existing site.

**Proposed UI for the Contact page**

__Contact Page - Webview__

![Contact Page - Webview](https://i.ibb.co/pbB4Cb2/Contact.png)

__Contact Page - Mobile View__

![Contact Page - Webview](https://i.ibb.co/ThQ7xtK/Contact-Mobile.png)

Find more info: [https://github.com/Satriaana/Satriaana-Web-Site/blob/dev/README.md](https://github.com/Satriaana/Satriaana-Web-Site/blob/dev/README.md)

**Comment by esau-morais** [comment]
Thank you for sharing this issue! I can get this

_Note: To proceed with the issue solving, you need to add the topic `hacktoberfest` to the project_

**Comment by nimeshkavinda** [comment]
> Thank you for sharing this issue! I can get this
> 
> _Note: To proceed with the issue solving, you need to add the topic `hacktoberfest` to the project_

Hi @esau-morais

No problem! Shall I assign you for this issue then?

**Comment by esau-morais** [comment]
Yes. Just one question: the issue is just create the contact form section, right?

_Note: Let me know when you add the required topic_

**Comment by nimeshkavinda** [comment]
> Yes. Just one question: the issue is just create the contact form section (with the send emails feature), right?
> 
> _Note: Let me know when you add the required topic_

Hi, Yes.

The header, cover and the footer already exists. So all you have to do is to make 3 more components for Contact information, form and FAQs section and route them! :relaxed:

**Comment by esau-morais** [comment]
Plase, add the topic called `hacktoberfest` to the GitHub repository. The sections are ready

![1](https://docs.github.com/assets/images/help/repository/edit-repository-details-gear.png)

**Comment by nimeshkavinda** [comment]
> Plase, add the topic called `hacktoberfest` to the GitHub repository and add the label in my pull request. The sections are ready
> 
> ![1](https://camo.githubusercontent.com/e8e3f7e7cdbc306f65bf0dda47c21041f683f14a/68747470733a2f2f646f63732e6769746875622e636f6d2f6173736574732f696d616765732f68656c702f7265706f7369746f72792f656469742d7265706f7369746f72792d64657461696c732d676561722e706e67)

Hi @esau-morais ,

We have already added `hacktoberfest` as one of the labels for this issue. If you are worried about your PRs not getting counted, don't worry they will! 

We are looking for open-source developers are who willing to contribute to development of our website. This is not entirely for Hacktoberfest event, nonetheless any PR you make will be counted towards completion of Hacktoberfest as this repo is set to public.

**Comment by esau-morais** [comment]
> > Plase, add the topic called `hacktoberfest` to the GitHub repository and add the label in my pull request. The sections are ready
> > ![1](https://camo.githubusercontent.com/e8e3f7e7cdbc306f65bf0dda47c21041f683f14a/68747470733a2f2f646f63732e6769746875622e636f6d2f6173736574732f696d616765732f68656c702f7265706f7369746f72792f656469742d7265706f7369746f72792d64657461696c732d676561722e706e67)
> 
> Hi @esau-morais ,
> 
> We have already added `hacktoberfest` as one of the labels for this issue. If you are worried about your PRs not getting counted, don't worry they will!
> 
> We are looking for open-source developers are who willing to contribute to development of our website. This is not entirely for Hacktoberfest event, nonetheless any PR you make will be counted towards completion of Hacktoberfest as this repo is set to public.

If you see the new rule by Hacktoberfest, you'll that the project will not be count. So, the pull request will not too

**Comment by nimeshkavinda** [comment]
> > > Plase, add the topic called `hacktoberfest` to the GitHub repository and add the label in my pull request. The sections are ready
> > > ![1](https://camo.githubusercontent.com/e8e3f7e7cdbc306f65bf0dda47c21041f683f14a/68747470733a2f2f646f63732e6769746875622e636f6d2f6173736574732f696d616765732f68656c702f7265706f7369746f72792f656469742d7265706f7369746f72792d64657461696c732d676561722e706e67)
> > 
> > 
> > Hi @esau-morais ,
> > We have already added `hacktoberfest` as one of the labels for this issue. If you are worried about your PRs not getting counted, don't worry they will!
> > We are looking for open-source developers are who willing to contribute to development of our website. This is not entirely for Hacktoberfest event, nonetheless any PR you make will be counted towards completion of Hacktoberfest as this repo is set to public.
> 
> If you see the new rule by Hacktoberfest, you'll
> see that the project will not be count. So, the pull request will not too. That's why you need assign the topic

Hi, I have added the topic as you requested.

**Comment by BuddhikaD** [comment]
Hi, @esau-morais 

Thank you so much for your generous contributions to the GitHub issues regarding the website of Satriaana. We highly appreciate all the work you’ve done. Your efforts in developing our website are very commendable.

It’s with great pleasure that we’d like to inform you that we've decided to give you the chance of joining us as volunteers, after seeing your enthusiasm for open-source. So, if you’re interested, simply fill out the form through the link we’ve attached forthwith.

Note: We’re starting our volunteer onboard process in three weeks time from now on and we’re sending this form only to you as you have contributed to our website. Hence we’ll be closing the link of the form right after you’ve submitted the form. So, we would like to kindly request you to send us a message in reply after you’ve filled it.

Volunteer Form: https://satriaana.typeform.com/to/XYGqfnkI

Hope we can work together again very soon!

**Comment by nimeshkavinda** [comment]
Hi @esau-morais, 
Can you please give the names of the yarn packages that you have used? Since we are running the site on Github pages, some of the yarn packages are not working. Therefore we need to install the npm packages for the yarn packages that you have used.

**Comment by esau-morais** [comment]
I just added `@material-ui/core` and `@material-ui/icons` dependencies

**Comment by nimeshkavinda** [comment]
> I just added `@material-ui/core` and `@material-ui/icons` dependencies

Thanks!
