### ISSUE TITLE
Routing issue in contact page

### ISSUE THREAD

**Issue by BuddhikaD** [Satriaana/Satriaana-Web-Site#95]
When we deploy the site in localhost and click contact in the header it will redirected to the Contact page. But when the site is hosted in GitHub pages when we click contact it's not redirected to the Contact page instead a` 404 error messages `displayed.😕

**Comment by DreamsOfImran** [comment]
Hi, Can I work on this?

**Comment by BuddhikaD** [comment]
Sure .. Please go ahead! 😊

**Comment by DreamsOfImran** [comment]
Please assign to me.

**Comment by BuddhikaD** [comment]
Sure !

**Comment by BuddhikaD** [comment]
Sure !

**Comment by iampankajgupta** [comment]
can i work on this issue

**Comment by DreamsOfImran** [comment]
Created PR for this. Please review it.
https://github.com/Satriaana/Satriaana-Web-Site/pull/96

**Comment by BuddhikaD** [comment]
Hi, @DreamsOfImran 

Thank you so much for your generous contributions to the GitHub issues regarding the website of Satriaana. We highly appreciate all the work you’ve done. Your efforts in developing our website are very commendable.

It’s with great pleasure that we’d like to inform you that we've decided to give you the chance of joining us as volunteers, after seeing your enthusiasm for open-source. So, if you’re interested, simply fill out the form through the link we’ve attached forthwith.

Note: We’re starting our volunteer onboard process in three weeks time from now on and we’re sending this form only to you as you have contributed to our website. Hence we’ll be closing the link of the form right after you’ve submitted the form. So, we would like to kindly request you to send us a message in reply after you’ve filled it.

Volunteer Form: https://satriaana.typeform.com/to/XYGqfnkI

Hope we can work together again very soon!

**Comment by DreamsOfImran** [comment]
@BuddhikaD, Thank you for the opportunity. I've filled the form. You can close it.
